### ISSUE TITLE
[RESOLVED] New Component & Behavior from "Manage Component" 

### ISSUE THREAD

**Issue by bangau1** [mrzon/GraphBT#2]
The new Component & Behavior created from "Manage Component" aren't appear in DropDownList at "Create Standard Node Wizard". But after creating new Component & Behavior from "Add New Component" & "Add New Behavior" button, the dropdown list shows the Component created before at "Manage Component" menu.

Scenario:
    - New -> Graphiti Project
    - New File -> BT Diagram
    - Create General BT Node -> Manage Component
      - ADD NEW COMPONENT : DOOR, DOOR_REF
      - ADD NEW BEHAVIOR : CLOSED, CLOSED_REF
      - Finish
    - On the main wizard "Create Standard Node Wizard", it doesn't show the new Component and Behavior.

**Comment by mrzon** [comment]
is this already solved @bangau1 ??
