### ISSUE TITLE
[Urgently needed] Preliminary GUIDE

### ISSUE THREAD

**Issue by mrzon** [mrzon/GraphBT#24]
We need to give a manual to install and to operate the tool..
I want to ask our friend from UQ to test the tool immediately and to give us feedback to the tool. As they all already familiar with BT. 
Please @bangau1 help for the installation guide, and @AbieIkhsan @ardialhaidar for the tool operation...

PS: @ardialhaidar please make you progress hurry and @bangau1 please support reversion in your debugging tool..

lots of thanks guys..

**Comment by nurulq** [comment]
maybe there is something i can do?

**Comment by mrzon** [comment]
@nurulq please help for the installation guide too :D
the example is shown here -> http://code.google.com/p/textbe/wiki/InstallingTextBE
